# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            老杜网志
tagline:          '小步徐行 终有所成'
description:      ''
url:              http://mrdu.me/
baseurl:          /

author:
  name:           'metaldudu'
  url:            https://mrdu.me

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/metaldudu
