# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        none

# Setup
title:            老杜网志
tagline:          '小步徐行 终有所成'
description:      ''
url:              http://blog.mrdu.me/
baseurl:          '/'

author:
  name:           'metaldudu'
  url:            http://mrdu.me

paginate:         4

# Custom vars

