# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:         /:categories/:title.html

# Setup
title:            老杜网志
tagline:          '小步徐行 终有所成'
description:      ''
url:              http://mrdu.me/
baseurl:          '/'

author:
  name:           'metaldudu'
  url:            http://mrdu.me

paginate:         5

# Custom vars

