# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        none

# Setup
title:            老杜网志
tagline:          '小步徐行 终有所成'
description:      ''
url:              https://metaldudu.github.io/
baseurl:          ''

author:
  name:           'metaldudu'
  url:            https://metaldudu.github.io/

paginate:         5

# Custom vars

