# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        none

# Setup
title:            老杜网志
tagline:          '小步徐行 终有所成'
description:      ''
url:              https://metaldudu.github.io/
baseurl:          ''

author:
  name:           '老杜还在'
  url:            ''

paginate:         4

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/metaldudu
